#pragma checksum "D:\Repos\easypost\ShipmentApp\ShipmentApp.Web\Views\Shipment\Retrieve.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "ff36d3eb218bb4ef5b7ea1663f54f836bc6e7138"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Shipment_Retrieve), @"mvc.1.0.view", @"/Views/Shipment/Retrieve.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Views/Shipment/Retrieve.cshtml", typeof(AspNetCore.Views_Shipment_Retrieve))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#line 1 "D:\Repos\easypost\ShipmentApp\ShipmentApp.Web\Views\_ViewImports.cshtml"
using ShipmentApp.Web;

#line default
#line hidden
#line 2 "D:\Repos\easypost\ShipmentApp\ShipmentApp.Web\Views\_ViewImports.cshtml"
using ShipmentApp.Web.Models;

#line default
#line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"ff36d3eb218bb4ef5b7ea1663f54f836bc6e7138", @"/Views/Shipment/Retrieve.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"9dbb56962b2f96de43f30b8948007c4b31db263a", @"/Views/_ViewImports.cshtml")]
    public class Views_Shipment_Retrieve : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<ShipmentApp.Domain.Contracts.ViewModels.ShipmentViewModel>
    {
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-action", "Index", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_1 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-action", "Create", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_2 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-action", "Delete", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        #line hidden
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            BeginContext(66, 130, true);
            WriteLiteral("\r\n<h1>Retrieve</h1>\r\n\r\n<dl class=\"row\">\r\n    <dt class=\"col-2\">\r\n        Description\r\n    </dt>\r\n    <dd class=\"col-10\">\r\n        ");
            EndContext();
            BeginContext(197, 17, false);
#line 10 "D:\Repos\easypost\ShipmentApp\ShipmentApp.Web\Views\Shipment\Retrieve.cshtml"
   Write(Model.Description);

#line default
#line hidden
            EndContext();
            BeginContext(214, 97, true);
            WriteLiteral("\r\n    </dd>\r\n    <dt class=\"col-2\">\r\n        Weight\r\n    </dt>\r\n    <dd class=\"col-10\">\r\n        ");
            EndContext();
            BeginContext(312, 12, false);
#line 16 "D:\Repos\easypost\ShipmentApp\ShipmentApp.Web\Views\Shipment\Retrieve.cshtml"
   Write(Model.Weight);

#line default
#line hidden
            EndContext();
            BeginContext(324, 255, true);
            WriteLiteral("\r\n    </dd>\r\n</dl>\r\n\r\n<hr />\r\n\r\n<div class=\"row justify-content-between\">\r\n    <div class=\"col-5\">\r\n        <dl class=\"row\">\r\n            <dt class=\"col-2\">\r\n                Sender Name\r\n            </dt>\r\n            <dd class=\"col-10\">\r\n                ");
            EndContext();
            BeginContext(580, 16, false);
#line 29 "D:\Repos\easypost\ShipmentApp\ShipmentApp.Web\Views\Shipment\Retrieve.cshtml"
           Write(Model.SenderName);

#line default
#line hidden
            EndContext();
            BeginContext(596, 148, true);
            WriteLiteral("\r\n            </dd>\r\n            <dt class=\"col-2\">\r\n                Post Code\r\n            </dt>\r\n            <dd class=\"col-10\">\r\n                ");
            EndContext();
            BeginContext(745, 28, false);
#line 35 "D:\Repos\easypost\ShipmentApp\ShipmentApp.Web\Views\Shipment\Retrieve.cshtml"
           Write(Model.SenderAddress.PostCode);

#line default
#line hidden
            EndContext();
            BeginContext(773, 151, true);
            WriteLiteral("\r\n            </dd>\r\n            <dt class=\"col-2\">\r\n                Country Code\r\n            </dt>\r\n            <dd class=\"col-10\">\r\n                ");
            EndContext();
            BeginContext(925, 31, false);
#line 41 "D:\Repos\easypost\ShipmentApp\ShipmentApp.Web\Views\Shipment\Retrieve.cshtml"
           Write(Model.SenderAddress.CountryCode);

#line default
#line hidden
            EndContext();
            BeginContext(956, 144, true);
            WriteLiteral("\r\n            </dd>\r\n            <dt class=\"col-2\">\r\n                State\r\n            </dt>\r\n            <dd class=\"col-10\">\r\n                ");
            EndContext();
            BeginContext(1101, 25, false);
#line 47 "D:\Repos\easypost\ShipmentApp\ShipmentApp.Web\Views\Shipment\Retrieve.cshtml"
           Write(Model.SenderAddress.State);

#line default
#line hidden
            EndContext();
            BeginContext(1126, 143, true);
            WriteLiteral("\r\n            </dd>\r\n            <dt class=\"col-2\">\r\n                City\r\n            </dt>\r\n            <dd class=\"col-10\">\r\n                ");
            EndContext();
            BeginContext(1270, 24, false);
#line 53 "D:\Repos\easypost\ShipmentApp\ShipmentApp.Web\Views\Shipment\Retrieve.cshtml"
           Write(Model.SenderAddress.City);

#line default
#line hidden
            EndContext();
            BeginContext(1294, 144, true);
            WriteLiteral("\r\n            </dd>\r\n            <dt class=\"col-2\">\r\n                Line1\r\n            </dt>\r\n            <dd class=\"col-10\">\r\n                ");
            EndContext();
            BeginContext(1439, 25, false);
#line 59 "D:\Repos\easypost\ShipmentApp\ShipmentApp.Web\Views\Shipment\Retrieve.cshtml"
           Write(Model.SenderAddress.Line1);

#line default
#line hidden
            EndContext();
            BeginContext(1464, 144, true);
            WriteLiteral("\r\n            </dd>\r\n            <dt class=\"col-2\">\r\n                Line2\r\n            </dt>\r\n            <dd class=\"col-10\">\r\n                ");
            EndContext();
            BeginContext(1609, 25, false);
#line 65 "D:\Repos\easypost\ShipmentApp\ShipmentApp.Web\Views\Shipment\Retrieve.cshtml"
           Write(Model.SenderAddress.Line2);

#line default
#line hidden
            EndContext();
            BeginContext(1634, 231, true);
            WriteLiteral("\r\n            </dd>\r\n        </dl>\r\n    </div>\r\n    <div class=\"col-5\">\r\n        <dl class=\"row\">\r\n            <dt class=\"col-2\">\r\n                Recipient Name\r\n            </dt>\r\n            <dd class=\"col-10\">\r\n                ");
            EndContext();
            BeginContext(1866, 19, false);
#line 75 "D:\Repos\easypost\ShipmentApp\ShipmentApp.Web\Views\Shipment\Retrieve.cshtml"
           Write(Model.RecipientName);

#line default
#line hidden
            EndContext();
            BeginContext(1885, 148, true);
            WriteLiteral("\r\n            </dd>\r\n            <dt class=\"col-2\">\r\n                Post Code\r\n            </dt>\r\n            <dd class=\"col-10\">\r\n                ");
            EndContext();
            BeginContext(2034, 31, false);
#line 81 "D:\Repos\easypost\ShipmentApp\ShipmentApp.Web\Views\Shipment\Retrieve.cshtml"
           Write(Model.RecipientAddress.PostCode);

#line default
#line hidden
            EndContext();
            BeginContext(2065, 151, true);
            WriteLiteral("\r\n            </dd>\r\n            <dt class=\"col-2\">\r\n                Country Code\r\n            </dt>\r\n            <dd class=\"col-10\">\r\n                ");
            EndContext();
            BeginContext(2217, 34, false);
#line 87 "D:\Repos\easypost\ShipmentApp\ShipmentApp.Web\Views\Shipment\Retrieve.cshtml"
           Write(Model.RecipientAddress.CountryCode);

#line default
#line hidden
            EndContext();
            BeginContext(2251, 144, true);
            WriteLiteral("\r\n            </dd>\r\n            <dt class=\"col-2\">\r\n                State\r\n            </dt>\r\n            <dd class=\"col-10\">\r\n                ");
            EndContext();
            BeginContext(2396, 28, false);
#line 93 "D:\Repos\easypost\ShipmentApp\ShipmentApp.Web\Views\Shipment\Retrieve.cshtml"
           Write(Model.RecipientAddress.State);

#line default
#line hidden
            EndContext();
            BeginContext(2424, 143, true);
            WriteLiteral("\r\n            </dd>\r\n            <dt class=\"col-2\">\r\n                City\r\n            </dt>\r\n            <dd class=\"col-10\">\r\n                ");
            EndContext();
            BeginContext(2568, 27, false);
#line 99 "D:\Repos\easypost\ShipmentApp\ShipmentApp.Web\Views\Shipment\Retrieve.cshtml"
           Write(Model.RecipientAddress.City);

#line default
#line hidden
            EndContext();
            BeginContext(2595, 144, true);
            WriteLiteral("\r\n            </dd>\r\n            <dt class=\"col-2\">\r\n                Line1\r\n            </dt>\r\n            <dd class=\"col-10\">\r\n                ");
            EndContext();
            BeginContext(2740, 28, false);
#line 105 "D:\Repos\easypost\ShipmentApp\ShipmentApp.Web\Views\Shipment\Retrieve.cshtml"
           Write(Model.RecipientAddress.Line1);

#line default
#line hidden
            EndContext();
            BeginContext(2768, 144, true);
            WriteLiteral("\r\n            </dd>\r\n            <dt class=\"col-2\">\r\n                Line2\r\n            </dt>\r\n            <dd class=\"col-10\">\r\n                ");
            EndContext();
            BeginContext(2913, 28, false);
#line 111 "D:\Repos\easypost\ShipmentApp\ShipmentApp.Web\Views\Shipment\Retrieve.cshtml"
           Write(Model.RecipientAddress.Line2);

#line default
#line hidden
            EndContext();
            BeginContext(2941, 69, true);
            WriteLiteral("\r\n            </dd>\r\n        </dl>\r\n    </div>\r\n</div>\r\n\r\n<div>\r\n    ");
            EndContext();
            BeginContext(3010, 38, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("a", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "ff36d3eb218bb4ef5b7ea1663f54f836bc6e713812387", async() => {
                BeginContext(3032, 12, true);
                WriteLiteral("Back to List");
                EndContext();
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Action = (string)__tagHelperAttribute_0.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_0);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(3048, 18, true);
            WriteLiteral("\r\n    <br />\r\n    ");
            EndContext();
            BeginContext(3066, 58, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("a", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "ff36d3eb218bb4ef5b7ea1663f54f836bc6e713813786", async() => {
                BeginContext(3114, 6, true);
                WriteLiteral("Update");
                EndContext();
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Action = (string)__tagHelperAttribute_1.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_1);
            if (__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues == null)
            {
                throw new InvalidOperationException(InvalidTagHelperIndexerAssignment("asp-route-id", "Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper", "RouteValues"));
            }
            BeginWriteTagHelperAttribute();
#line 120 "D:\Repos\easypost\ShipmentApp\ShipmentApp.Web\Views\Shipment\Retrieve.cshtml"
                             WriteLiteral(Model.Id);

#line default
#line hidden
            __tagHelperStringValueBuffer = EndWriteTagHelperAttribute();
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["id"] = __tagHelperStringValueBuffer;
            __tagHelperExecutionContext.AddTagHelperAttribute("asp-route-id", __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["id"], global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(3124, 18, true);
            WriteLiteral("\r\n    <br />\r\n    ");
            EndContext();
            BeginContext(3142, 59, false);
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("a", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "ff36d3eb218bb4ef5b7ea1663f54f836bc6e713816123", async() => {
                BeginContext(3190, 7, true);
                WriteLiteral("Delete ");
                EndContext();
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Action = (string)__tagHelperAttribute_2.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_2);
            if (__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues == null)
            {
                throw new InvalidOperationException(InvalidTagHelperIndexerAssignment("asp-route-id", "Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper", "RouteValues"));
            }
            BeginWriteTagHelperAttribute();
#line 122 "D:\Repos\easypost\ShipmentApp\ShipmentApp.Web\Views\Shipment\Retrieve.cshtml"
                             WriteLiteral(Model.Id);

#line default
#line hidden
            __tagHelperStringValueBuffer = EndWriteTagHelperAttribute();
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["id"] = __tagHelperStringValueBuffer;
            __tagHelperExecutionContext.AddTagHelperAttribute("asp-route-id", __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.RouteValues["id"], global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            EndContext();
            BeginContext(3201, 10, true);
            WriteLiteral("\r\n</div>\r\n");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<ShipmentApp.Domain.Contracts.ViewModels.ShipmentViewModel> Html { get; private set; }
    }
}
#pragma warning restore 1591
